name: cmake

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
          
jobs:
    build:
        runs-on: ubuntu-${{ matrix.ubuntu_version }}
        name: Ubuntu-${{ matrix.ubuntu_version }}
        strategy:
            fail-fast: false
            matrix:
                ubuntu_version: [22.04]

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0


          - name: Install packages
            run: |
                sudo apt-get install -y gcc g++ cmake wget git libdumbnet-dev libpcap-dev


          - name: Configure
            run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -B "${{github.workspace}}/build" 

          - name: Build
            run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
